### PR TITLE
[FIX] Move Section to its own namespace

### PR DESCRIPTION
**Pull request by YoHype**
### Types of changes

- [x] Fix (non-breaking change that fixes existing issue)
- [x] Feature (non-breaking change that adds a feature)
- [ ] Breaking change (fix or feature that breaks or removes other functionality)

### Pre-flight checklist

- [ ] PR changes requires documentation change
  - [ ] I have updated the documentation accordingly
- [x] I have tested my change, and run all unit tests 
- [x] I ran ``dotnet format`` and committed+pushed the result

## Screenshots of the solution (if appropriate)

### CODE REVIEW

**Review by JoachimBorup — DISMISSED** [review]

**Review by avborup — DISMISSED** [review]

**Comment by JoachimBorup** [comment]
I added labels and dismissed approvals, thinking this was another branch. Disregard

**Review by JoachimBorup — DISMISSED** [review]

**Comment by avborup** [comment]
It is less work (and safer?) to close this, branch out from master, and repeat the process used to make this PR than to merge master into this PR.

**Review by avborup — APPROVED** [review]

**Review by JoachimBorup — DISMISSED** [review]

**Comment by albe2669** [comment]
The all sections page on the frontend errors when accessed on this branch. Pls fix

**Review by albe2669 — CHANGES_REQUESTED** [review]
See previous

**Review by JoachimBorup — APPROVED** [review]

**Pull request closed without merging**
